### ISSUE TITLE
Make Task implement `Promise`, not just `PromiseLike`

### ISSUE THREAD

**Issue by cowboyd** [jnicklas/mini-effection#6]
https://github.com/jnicklas/mini-effection/blob/5c1024c3830b484c50bbe4d5b34550747e200de1/src/task.ts#L20

It's a little more work, but having TypeScript know that there is a `catch` and `finally` method is much more convenient, and means that it interoperates better with more other libraries that expect promises.

**Comment by jnicklas** [comment]
This was totally just laziness on my part 😅
